"""link choice questions to authors

Revision ID: 0bee734e8685
Revises: 175b07ee1691
Create Date: 2026-09-29 11:55:58.331427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bee734e8685'
down_revision: Union[str, None] = '175b07ee1691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('choice_questions', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_choice_questions_author_id'), 'choice_questions', ['author_id'], unique=False)
    op.create_foreign_key(
        "fk_choice_questions_author_id_users",
        "choice_questions",
        "users",
        ["author_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_choice_questions_author_id_users",
        "choice_questions",
        type_="foreignkey",
    )
    op.drop_index(op.f('ix_choice_questions_author_id'), table_name='choice_questions')
    op.drop_column('choice_questions', 'author_id')
    # ### end Alembic commands ###
