"""remove legacy service tables

Revision ID: 12badf3b9d7e
Revises: 9830cbc3c7c6
Create Date: 2026-09-21 17:26:56.177147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12badf3b9d7e'
down_revision: Union[str, None] = '9830cbc3c7c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commute_routes')
    op.drop_index('ix_schedules_schedule_date', table_name='schedules')
    op.drop_table('schedules')
    op.drop_index('ix_guest_interests_session_token', table_name='guest_interests')
    op.drop_table('guest_interests')
    op.drop_table('commute_favorites')
    op.drop_index('ix_stocks_code', table_name='stocks')
    op.drop_index('ix_stocks_name', table_name='stocks')
    op.drop_table('stocks')
    op.drop_table('commute_queries')
    op.drop_table('user_interests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_interests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_interests_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_interests_pkey'),
    sa.UniqueConstraint('user_id', 'type', 'value', name='uq_user_interests_user_id_type_value')
    )
    op.create_table('commute_queries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('origin_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('destination_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('origin_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('origin_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('dest_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('dest_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('estimated_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('delay_minutes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('queried_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='commute_queries_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='commute_queries_pkey')
    )
    op.create_table('stocks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('market', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='stocks_pkey')
    )
    op.create_index('ix_stocks_name', 'stocks', ['name'], unique=False)
    op.create_index('ix_stocks_code', 'stocks', ['code'], unique=True)
    op.create_table('commute_favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('origin_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('origin_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('origin_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('destination_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('destination_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('destination_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='commute_favorites_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='commute_favorites_pkey')
    )
    op.create_table('guest_interests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='guest_interests_pkey')
    )
    op.create_index('ix_guest_interests_session_token', 'guest_interests', ['session_token'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('scheduled_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('schedule_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='schedules_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='schedules_pkey')
    )
    op.create_index('ix_schedules_schedule_date', 'schedules', ['schedule_date'], unique=False)
    op.create_table('commute_routes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='commute_routes_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='commute_routes_pkey')
    )
    # ### end Alembic commands ###
