"""support up to four choice options

Revision ID: 175b07ee1691
Revises: e0d9472e53f0
Create Date: 2026-09-29 11:23:56.545092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175b07ee1691'
down_revision: Union[str, None] = 'e0d9472e53f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('choice_questions', sa.Column('option_c', sa.String(length=100), nullable=True))
    op.add_column('choice_questions', sa.Column('option_d', sa.String(length=100), nullable=True))
    op.create_check_constraint(
        'ck_choice_questions_option_order',
        'choice_questions',
        'option_d IS NULL OR option_c IS NOT NULL',
    )
    op.drop_constraint('ck_choice_votes_option', 'choice_votes', type_='check')
    op.create_check_constraint(
        'ck_choice_votes_option',
        'choice_votes',
        "selected_option IN ('A', 'B', 'C', 'D')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DELETE FROM choice_votes WHERE selected_option IN ('C', 'D')"))
    op.drop_constraint('ck_choice_votes_option', 'choice_votes', type_='check')
    op.create_check_constraint(
        'ck_choice_votes_option',
        'choice_votes',
        "selected_option IN ('A', 'B')",
    )
    op.drop_constraint(
        'ck_choice_questions_option_order',
        'choice_questions',
        type_='check',
    )
    op.drop_column('choice_questions', 'option_d')
    op.drop_column('choice_questions', 'option_c')
    # ### end Alembic commands ###
