"""make user nicknames unique

Revision ID: 4528840cd462
Revises: 6108ff5d4fe3
Create Date: 2026-10-01 14:58:55.766988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4528840cd462'
down_revision: Union[str, None] = '6108ff5d4fe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text(
            "WITH ranked AS ("
            "SELECT id, ROW_NUMBER() OVER (PARTITION BY nickname ORDER BY id) AS row_number "
            "FROM users"
            ") "
            "UPDATE users SET nickname = CONCAT('__gwiteem_user_', users.id) "
            "FROM ranked WHERE users.id = ranked.id AND ranked.row_number > 1"
        )
    )
    op.create_unique_constraint(
        "uq_users_nickname",
        "users",
        ["nickname"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_nickname", "users", type_="unique")
    # ### end Alembic commands ###
