"""remove news and briefing features

Revision ID: 698d4567056f
Revises: 7968d1b7732e
Create Date: 2026-09-18 15:24:35.459381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '698d4567056f'
down_revision: Union[str, None] = '7968d1b7732e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_briefings_briefing_date', table_name='daily_briefings')
    op.drop_table('daily_briefings')
    op.drop_index('ix_shared_briefings_share_token', table_name='shared_briefings')
    op.drop_table('shared_briefings')
    # 세 뉴스 테이블은 순환 외래 키를 사용하므로 제약을 먼저 제거한다.
    op.drop_constraint('fk_issue_clusters_centroid', 'issue_clusters', type_='foreignkey')
    op.drop_constraint('raw_articles_cluster_id_fkey', 'raw_articles', type_='foreignkey')
    op.drop_table('news_embeddings')
    op.drop_table('raw_articles')
    op.drop_table('issue_clusters')
    op.drop_table('interest_embeddings')
    op.drop_index('ix_user_briefings_briefing_date', table_name='user_briefings')
    op.drop_table('user_briefings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_briefings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('briefing_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('time_slot', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('personalized_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('matched_issue_ids', postgresql.ARRAY(sa.INTEGER()), server_default=sa.text("'{}'::integer[]"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_briefings_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_briefings_pkey')
    )
    op.create_index('ix_user_briefings_briefing_date', 'user_briefings', ['briefing_date'], unique=False)
    op.create_table('interest_embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('owner_ref_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('keyword', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('embedding', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='interest_embeddings_pkey')
    )
    op.create_table('raw_articles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('raw_articles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('content_snippet', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cluster_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['issue_clusters.id'], name='raw_articles_cluster_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='raw_articles_pkey'),
    sa.UniqueConstraint('url', name='raw_articles_url_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('issue_clusters',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('issue_clusters_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('article_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('centroid_embedding_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('related_stock_codes', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['centroid_embedding_id'], ['news_embeddings.id'], name='fk_issue_clusters_centroid'),
    sa.PrimaryKeyConstraint('id', name='issue_clusters_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('news_embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('embedding', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['raw_articles.id'], name='news_embeddings_article_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='news_embeddings_pkey')
    )
    op.create_table('shared_briefings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('briefing_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('briefing_ref_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('share_token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='shared_briefings_created_by_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='shared_briefings_pkey')
    )
    op.create_index('ix_shared_briefings_share_token', 'shared_briefings', ['share_token'], unique=True)
    op.create_table('daily_briefings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('briefing_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('time_slot', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('summary_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('top_issue_ids', postgresql.ARRAY(sa.INTEGER()), server_default=sa.text("'{}'::integer[]"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='daily_briefings_pkey')
    )
    op.create_index('ix_daily_briefings_briefing_date', 'daily_briefings', ['briefing_date'], unique=False)
    # ### end Alembic commands ###
