"""add choice questions and votes

Revision ID: 9830cbc3c7c6
Revises: 698d4567056f
Create Date: 2026-09-21 17:09:21.907661

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9830cbc3c7c6'
down_revision: Union[str, None] = '698d4567056f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('choice_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('option_a', sa.String(length=100), nullable=False),
    sa.Column('option_b', sa.String(length=100), nullable=False),
    sa.Column('is_daily', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_choice_questions_category'), 'choice_questions', ['category'], unique=False)
    op.create_index(op.f('ix_choice_questions_is_active'), 'choice_questions', ['is_active'], unique=False)
    op.create_index(op.f('ix_choice_questions_is_daily'), 'choice_questions', ['is_daily'], unique=False)
    op.create_index(op.f('ix_choice_questions_published_at'), 'choice_questions', ['published_at'], unique=False)
    op.create_table('choice_reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['choice_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_choice_reasons_question_id'), 'choice_reasons', ['question_id'], unique=False)
    op.create_table('choice_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('guest_session_id', sa.String(length=64), nullable=True),
    sa.Column('selected_option', sa.String(length=1), nullable=False),
    sa.Column('reason_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("selected_option IN ('A', 'B')", name='ck_choice_votes_option'),
    sa.CheckConstraint('(user_id IS NOT NULL AND guest_session_id IS NULL) OR (user_id IS NULL AND guest_session_id IS NOT NULL)', name='ck_choice_votes_participant'),
    sa.ForeignKeyConstraint(['question_id'], ['choice_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reason_id'], ['choice_reasons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_choice_votes_guest_session_id'), 'choice_votes', ['guest_session_id'], unique=False)
    op.create_index(op.f('ix_choice_votes_question_id'), 'choice_votes', ['question_id'], unique=False)
    op.create_index(op.f('ix_choice_votes_user_id'), 'choice_votes', ['user_id'], unique=False)
    op.create_index('uq_choice_votes_question_guest', 'choice_votes', ['question_id', 'guest_session_id'], unique=True, postgresql_where=sa.text('guest_session_id IS NOT NULL'))
    op.create_index('uq_choice_votes_question_user', 'choice_votes', ['question_id', 'user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    now = datetime.utcnow()
    question_table = sa.table(
        'choice_questions',
        sa.column('id', sa.Integer()),
        sa.column('category', sa.String()),
        sa.column('title', sa.String()),
        sa.column('option_a', sa.String()),
        sa.column('option_b', sa.String()),
        sa.column('is_daily', sa.Boolean()),
        sa.column('is_active', sa.Boolean()),
        sa.column('published_at', sa.DateTime()),
        sa.column('created_at', sa.DateTime()),
    )
    op.bulk_insert(question_table, [
        {'id': 1, 'category': 'work', 'title': '직장을 선택할 때 하나만 고른다면?', 'option_a': '연봉 15% 상승', 'option_b': '야근 없는 워라밸', 'is_daily': True, 'is_active': True, 'published_at': now, 'created_at': now},
        {'id': 2, 'category': 'spending', 'title': '배송이 빠른 대신 비싼 상품, 기다려도 저렴한 상품?', 'option_a': '오늘 바로 받기', 'option_b': '며칠 기다리기', 'is_daily': False, 'is_active': True, 'published_at': now, 'created_at': now},
        {'id': 3, 'category': 'relationship', 'title': '친한 친구의 솔직한 조언, 듣기 좋은 위로?', 'option_a': '솔직한 조언', 'option_b': '따뜻한 위로', 'is_daily': False, 'is_active': True, 'published_at': now, 'created_at': now},
        {'id': 4, 'category': 'daily', 'title': '평일에 한 시간을 더 쓸 수 있다면?', 'option_a': '한 시간 더 자기', 'option_b': '취미 즐기기', 'is_daily': False, 'is_active': True, 'published_at': now, 'created_at': now},
        {'id': 5, 'category': 'work', 'title': '출근 방식을 하나만 고른다면?', 'option_a': '주 5일 재택', 'option_b': '주 4일 출근', 'is_daily': False, 'is_active': True, 'published_at': now, 'created_at': now},
        {'id': 6, 'category': 'spending', 'title': '같은 예산으로 하나만 선택한다면?', 'option_a': '좋은 물건 하나', 'option_b': '실용적인 여러 개', 'is_daily': False, 'is_active': True, 'published_at': now, 'created_at': now},
        {'id': 7, 'category': 'relationship', 'title': '연락 방식이 다를 때 더 중요한 것은?', 'option_a': '연락 빈도', 'option_b': '대화의 깊이', 'is_daily': False, 'is_active': True, 'published_at': now, 'created_at': now},
    ])
    reason_table = sa.table(
        'choice_reasons',
        sa.column('id', sa.Integer()),
        sa.column('question_id', sa.Integer()),
        sa.column('label', sa.String()),
        sa.column('sort_order', sa.Integer()),
    )
    reason_labels = [
        '시간과 여유가 중요해서',
        '경제적인 이점이 커서',
        '지속 가능한 선택이라서',
        '현재 내 상황에 더 잘 맞아서',
    ]
    op.bulk_insert(
        reason_table,
        [
            {
                'id': (question_id - 1) * 4 + sort_order,
                'question_id': question_id,
                'label': label,
                'sort_order': sort_order,
            }
            for question_id in range(1, 8)
            for sort_order, label in enumerate(reason_labels, start=1)
        ],
    )
    op.execute(sa.text("SELECT setval('choice_questions_id_seq', 7, true)"))
    op.execute(sa.text("SELECT setval('choice_reasons_id_seq', 28, true)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_choice_votes_question_user', table_name='choice_votes', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('uq_choice_votes_question_guest', table_name='choice_votes', postgresql_where=sa.text('guest_session_id IS NOT NULL'))
    op.drop_index(op.f('ix_choice_votes_user_id'), table_name='choice_votes')
    op.drop_index(op.f('ix_choice_votes_question_id'), table_name='choice_votes')
    op.drop_index(op.f('ix_choice_votes_guest_session_id'), table_name='choice_votes')
    op.drop_table('choice_votes')
    op.drop_index(op.f('ix_choice_reasons_question_id'), table_name='choice_reasons')
    op.drop_table('choice_reasons')
    op.drop_index(op.f('ix_choice_questions_published_at'), table_name='choice_questions')
    op.drop_index(op.f('ix_choice_questions_is_daily'), table_name='choice_questions')
    op.drop_index(op.f('ix_choice_questions_is_active'), table_name='choice_questions')
    op.drop_index(op.f('ix_choice_questions_category'), table_name='choice_questions')
    op.drop_table('choice_questions')
    # ### end Alembic commands ###
