"""add choice likes

Revision ID: dae844e0f9d2
Revises: fce3f83af5da
Create Date: 2026-10-01 15:20:09.236140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae844e0f9d2'
down_revision: Union[str, None] = 'fce3f83af5da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('choice_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['choice_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'user_id', name='uq_choice_likes_question_user')
    )
    op.create_index(op.f('ix_choice_likes_question_id'), 'choice_likes', ['question_id'], unique=False)
    op.create_index(op.f('ix_choice_likes_user_id'), 'choice_likes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_choice_likes_user_id'), table_name='choice_likes')
    op.drop_index(op.f('ix_choice_likes_question_id'), table_name='choice_likes')
    op.drop_table('choice_likes')
    # ### end Alembic commands ###
