"""require choice vote reason

Revision ID: e0d9472e53f0
Revises: 12badf3b9d7e
Create Date: 2026-09-29 11:08:34.020267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d9472e53f0'
down_revision: Union[str, None] = '12badf3b9d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DELETE FROM choice_votes WHERE reason_id IS NULL"))
    op.alter_column('choice_votes', 'reason_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('choice_votes_reason_id_fkey', 'choice_votes', type_='foreignkey')
    op.create_foreign_key('choice_votes_reason_id_fkey', 'choice_votes', 'choice_reasons', ['reason_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('choice_votes_reason_id_fkey', 'choice_votes', type_='foreignkey')
    op.create_foreign_key('choice_votes_reason_id_fkey', 'choice_votes', 'choice_reasons', ['reason_id'], ['id'], ondelete='SET NULL')
    op.alter_column('choice_votes', 'reason_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
